# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7e7e4c-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictFloat, StrictInt, StrictStr
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated
from skillberry_store_sdk.models.lifecycle_state import LifecycleState
from skillberry_store_sdk.models.manifest_state import ManifestState

from skillberry_store_sdk.api_client import ApiClient, RequestSerialized
from skillberry_store_sdk.api_response import ApiResponse
from skillberry_store_sdk.rest import RESTResponseType


class VmcpServersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_vmcp_server_vmcp_servers_post(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[Optional[StrictStr]]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Create Vmcp Server

        Create a new virtual MCP server.  Creates both the persistent JSON representation and starts the runtime server.  Args:     vmcp: The vmcp schema (auto-generated from VmcpSchema).     request: The incoming request object for context extraction.  Returns:     dict: Success message with the vmcp server name, uuid, and port.  Raises:     HTTPException: If vmcp server already exists (409) or creation fails (500).

        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[Optional[str]]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vmcp_server_vmcp_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_vmcp_server_vmcp_servers_post_with_http_info(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[Optional[StrictStr]]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Create Vmcp Server

        Create a new virtual MCP server.  Creates both the persistent JSON representation and starts the runtime server.  Args:     vmcp: The vmcp schema (auto-generated from VmcpSchema).     request: The incoming request object for context extraction.  Returns:     dict: Success message with the vmcp server name, uuid, and port.  Raises:     HTTPException: If vmcp server already exists (409) or creation fails (500).

        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[Optional[str]]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vmcp_server_vmcp_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_vmcp_server_vmcp_servers_post_without_preload_content(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[Optional[StrictStr]]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Vmcp Server

        Create a new virtual MCP server.  Creates both the persistent JSON representation and starts the runtime server.  Args:     vmcp: The vmcp schema (auto-generated from VmcpSchema).     request: The incoming request object for context extraction.  Returns:     dict: Success message with the vmcp server name, uuid, and port.  Raises:     HTTPException: If vmcp server already exists (409) or creation fails (500).

        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[Optional[str]]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vmcp_server_vmcp_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_vmcp_server_vmcp_servers_post_serialize(
        self,
        name,
        uuid,
        version,
        description,
        state,
        tags,
        extra,
        port,
        skill_uuid,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'tags': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if name is not None:
            
            _query_params.append(('name', name))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if state is not None:
            
            _query_params.append(('state', state.value))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if extra is not None:
            
            _query_params.append(('extra', extra))
            
        if port is not None:
            
            _query_params.append(('port', port))
            
        if skill_uuid is not None:
            
            _query_params.append(('skill_uuid', skill_uuid))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/vmcp_servers/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def delete_vmcp_server_vmcp_servers_name_delete(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Delete Vmcp Server

        Delete a virtual MCP server by name.  Stops the runtime server and removes persistent data.  Args:     name: The name of the vmcp server to delete.  Returns:     dict: Success message.  Raises:     HTTPException: If vmcp server not found (404) or deletion fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vmcp_server_vmcp_servers_name_delete_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def delete_vmcp_server_vmcp_servers_name_delete_with_http_info(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Delete Vmcp Server

        Delete a virtual MCP server by name.  Stops the runtime server and removes persistent data.  Args:     name: The name of the vmcp server to delete.  Returns:     dict: Success message.  Raises:     HTTPException: If vmcp server not found (404) or deletion fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vmcp_server_vmcp_servers_name_delete_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def delete_vmcp_server_vmcp_servers_name_delete_without_preload_content(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete Vmcp Server

        Delete a virtual MCP server by name.  Stops the runtime server and removes persistent data.  Args:     name: The name of the vmcp server to delete.  Returns:     dict: Success message.  Raises:     HTTPException: If vmcp server not found (404) or deletion fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vmcp_server_vmcp_servers_name_delete_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_vmcp_server_vmcp_servers_name_delete_serialize(
        self,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/vmcp_servers/{name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_vmcp_server_vmcp_servers_name_get(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Get Vmcp Server

        Get a specific virtual MCP server by name.  Returns both persistent and runtime information.  Args:     name: The name of the vmcp server.  Returns:     dict: The vmcp server object with runtime details.  Raises:     HTTPException: If vmcp server not found (404) or retrieval fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vmcp_server_vmcp_servers_name_get_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_vmcp_server_vmcp_servers_name_get_with_http_info(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Get Vmcp Server

        Get a specific virtual MCP server by name.  Returns both persistent and runtime information.  Args:     name: The name of the vmcp server.  Returns:     dict: The vmcp server object with runtime details.  Raises:     HTTPException: If vmcp server not found (404) or retrieval fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vmcp_server_vmcp_servers_name_get_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_vmcp_server_vmcp_servers_name_get_without_preload_content(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Vmcp Server

        Get a specific virtual MCP server by name.  Returns both persistent and runtime information.  Args:     name: The name of the vmcp server.  Returns:     dict: The vmcp server object with runtime details.  Raises:     HTTPException: If vmcp server not found (404) or retrieval fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vmcp_server_vmcp_servers_name_get_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_vmcp_server_vmcp_servers_name_get_serialize(
        self,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/vmcp_servers/{name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_vmcp_servers_vmcp_servers_get(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """List Vmcp Servers

        List all virtual MCP servers.  Returns both persistent and runtime information.  Returns:     dict: Dictionary containing a dict of virtual MCP servers with full details.  Raises:     HTTPException: If listing fails (500).

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vmcp_servers_vmcp_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_vmcp_servers_vmcp_servers_get_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """List Vmcp Servers

        List all virtual MCP servers.  Returns both persistent and runtime information.  Returns:     dict: Dictionary containing a dict of virtual MCP servers with full details.  Raises:     HTTPException: If listing fails (500).

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vmcp_servers_vmcp_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_vmcp_servers_vmcp_servers_get_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Vmcp Servers

        List all virtual MCP servers.  Returns both persistent and runtime information.  Returns:     dict: Dictionary containing a dict of virtual MCP servers with full details.  Raises:     HTTPException: If listing fails (500).

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vmcp_servers_vmcp_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_vmcp_servers_vmcp_servers_get_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/vmcp_servers/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_vmcp_servers_search_vmcp_servers_get(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[LifecycleState] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Search Vmcp Servers

        Search for vmcp servers by description.  Returns vmcp servers that are below the similarity threshold and match the filters.  Args:     search_term: Search term.     max_number_of_results: Number of results to return.     similarity_threshold: Threshold to be used.     manifest_filter: Manifest properties to filter (e.g., \"tags:python\", \"state:approved\").     lifecycle_state: State to filter by (e.g., LifecycleState.APPROVED).  Returns:     list: A list of matched vmcp server names and similarity scores.

        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vmcp_servers_search_vmcp_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_vmcp_servers_search_vmcp_servers_get_with_http_info(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[LifecycleState] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Search Vmcp Servers

        Search for vmcp servers by description.  Returns vmcp servers that are below the similarity threshold and match the filters.  Args:     search_term: Search term.     max_number_of_results: Number of results to return.     similarity_threshold: Threshold to be used.     manifest_filter: Manifest properties to filter (e.g., \"tags:python\", \"state:approved\").     lifecycle_state: State to filter by (e.g., LifecycleState.APPROVED).  Returns:     list: A list of matched vmcp server names and similarity scores.

        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vmcp_servers_search_vmcp_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_vmcp_servers_search_vmcp_servers_get_without_preload_content(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[LifecycleState] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search Vmcp Servers

        Search for vmcp servers by description.  Returns vmcp servers that are below the similarity threshold and match the filters.  Args:     search_term: Search term.     max_number_of_results: Number of results to return.     similarity_threshold: Threshold to be used.     manifest_filter: Manifest properties to filter (e.g., \"tags:python\", \"state:approved\").     lifecycle_state: State to filter by (e.g., LifecycleState.APPROVED).  Returns:     list: A list of matched vmcp server names and similarity scores.

        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vmcp_servers_search_vmcp_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_vmcp_servers_search_vmcp_servers_get_serialize(
        self,
        search_term,
        max_number_of_results,
        similarity_threshold,
        manifest_filter,
        lifecycle_state,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if search_term is not None:
            
            _query_params.append(('search_term', search_term))
            
        if max_number_of_results is not None:
            
            _query_params.append(('max_number_of_results', max_number_of_results))
            
        if similarity_threshold is not None:
            
            _query_params.append(('similarity_threshold', similarity_threshold))
            
        if manifest_filter is not None:
            
            _query_params.append(('manifest_filter', manifest_filter))
            
        if lifecycle_state is not None:
            
            _query_params.append(('lifecycle_state', lifecycle_state.value))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/search/vmcp_servers',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def start_vmcp_server_vmcp_servers_name_start_post(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Start Vmcp Server

        Start or restart a virtual MCP server.  This endpoint allows starting a server that exists in persistent storage but is not currently running in the runtime manager.  Args:     name: The name of the vmcp server to start.     request: The incoming request object for context extraction.  Returns:     dict: Success message with the server port.  Raises:     HTTPException: If vmcp server not found (404) or start fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vmcp_server_vmcp_servers_name_start_post_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def start_vmcp_server_vmcp_servers_name_start_post_with_http_info(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Start Vmcp Server

        Start or restart a virtual MCP server.  This endpoint allows starting a server that exists in persistent storage but is not currently running in the runtime manager.  Args:     name: The name of the vmcp server to start.     request: The incoming request object for context extraction.  Returns:     dict: Success message with the server port.  Raises:     HTTPException: If vmcp server not found (404) or start fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vmcp_server_vmcp_servers_name_start_post_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def start_vmcp_server_vmcp_servers_name_start_post_without_preload_content(
        self,
        name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Start Vmcp Server

        Start or restart a virtual MCP server.  This endpoint allows starting a server that exists in persistent storage but is not currently running in the runtime manager.  Args:     name: The name of the vmcp server to start.     request: The incoming request object for context extraction.  Returns:     dict: Success message with the server port.  Raises:     HTTPException: If vmcp server not found (404) or start fails (500).

        :param name: (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vmcp_server_vmcp_servers_name_start_post_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _start_vmcp_server_vmcp_servers_name_start_post_serialize(
        self,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/vmcp_servers/{name}/start',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_vmcp_server_vmcp_servers_name_put(
        self,
        name: StrictStr,
        name2: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Update Vmcp Server

        Update an existing virtual MCP server.  Updates both persistent data and restarts the runtime server.  Args:     name: The name of the vmcp server to update.     vmcp: The updated vmcp schema.     request: The incoming request object for context extraction.  Returns:     dict: Success message with new port.  Raises:     HTTPException: If vmcp server not found (404) or update fails (500).

        :param name: (required)
        :type name: str
        :param name2: Name
        :type name2: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vmcp_server_vmcp_servers_name_put_serialize(
            name=name,
            name2=name2,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_vmcp_server_vmcp_servers_name_put_with_http_info(
        self,
        name: StrictStr,
        name2: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Update Vmcp Server

        Update an existing virtual MCP server.  Updates both persistent data and restarts the runtime server.  Args:     name: The name of the vmcp server to update.     vmcp: The updated vmcp schema.     request: The incoming request object for context extraction.  Returns:     dict: Success message with new port.  Raises:     HTTPException: If vmcp server not found (404) or update fails (500).

        :param name: (required)
        :type name: str
        :param name2: Name
        :type name2: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vmcp_server_vmcp_servers_name_put_serialize(
            name=name,
            name2=name2,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_vmcp_server_vmcp_servers_name_put_without_preload_content(
        self,
        name: StrictStr,
        name2: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[ManifestState], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional key-value pairs for additional flexible information")] = None,
        port: Annotated[Optional[StrictInt], Field(description="Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill registered with the virtual MCP server")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update Vmcp Server

        Update an existing virtual MCP server.  Updates both persistent data and restarts the runtime server.  Args:     name: The name of the vmcp server to update.     vmcp: The updated vmcp schema.     request: The incoming request object for context extraction.  Returns:     dict: Success message with new port.  Raises:     HTTPException: If vmcp server not found (404) or update fails (500).

        :param name: (required)
        :type name: str
        :param name2: Name
        :type name2: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional key-value pairs for additional flexible information
        :type extra: Dict[str, object]
        :param port: Port on which the virtual MCP server is running. If None, an available port will be auto-assigned.
        :type port: int
        :param skill_uuid: UUID of the skill registered with the virtual MCP server
        :type skill_uuid: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vmcp_server_vmcp_servers_name_put_serialize(
            name=name,
            name2=name2,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            port=port,
            skill_uuid=skill_uuid,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_vmcp_server_vmcp_servers_name_put_serialize(
        self,
        name,
        name2,
        uuid,
        version,
        description,
        state,
        tags,
        extra,
        port,
        skill_uuid,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'tags': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        if name2 is not None:
            
            _query_params.append(('name', name2))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if state is not None:
            
            _query_params.append(('state', state.value))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if extra is not None:
            
            _query_params.append(('extra', extra))
            
        if port is not None:
            
            _query_params.append(('port', port))
            
        if skill_uuid is not None:
            
            _query_params.append(('skill_uuid', skill_uuid))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/vmcp_servers/{name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


