"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g689a0f7-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictFloat, StrictInt, StrictStr
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated

from skillberry_store_sdk.api_client import ApiClient, RequestSerialized
from skillberry_store_sdk.api_response import ApiResponse
from skillberry_store_sdk.rest import RESTResponseType


class VnfsServersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_vnfs_server_vnfs_servers_post(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Create Vnfs Server


        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vnfs_server_vnfs_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_vnfs_server_vnfs_servers_post_with_http_info(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Create Vnfs Server


        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vnfs_server_vnfs_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_vnfs_server_vnfs_servers_post_without_preload_content(
        self,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Vnfs Server


        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_vnfs_server_vnfs_servers_post_serialize(
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_vnfs_server_vnfs_servers_post_serialize(
        self,
        name,
        uuid,
        version,
        description,
        state,
        tags,
        extra,
        parent,
        created_at,
        modified_at,
        port,
        skill_uuid,
        protocol,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'tags': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if name is not None:
            
            _query_params.append(('name', name))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if state is not None:
            
            _query_params.append(('state', state.value))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if extra is not None:
            
            _query_params.append(('extra', extra))
            
        if parent is not None:
            
            _query_params.append(('parent', parent))
            
        if created_at is not None:
            
            _query_params.append(('created_at', created_at))
            
        if modified_at is not None:
            
            _query_params.append(('modified_at', modified_at))
            
        if port is not None:
            
            _query_params.append(('port', port))
            
        if skill_uuid is not None:
            
            _query_params.append(('skill_uuid', skill_uuid))
            
        if protocol is not None:
            
            _query_params.append(('protocol', protocol))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/vnfs_servers/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def delete_vnfs_server_vnfs_servers_uuid_or_name_delete(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Delete Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vnfs_server_vnfs_servers_uuid_or_name_delete_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def delete_vnfs_server_vnfs_servers_uuid_or_name_delete_with_http_info(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Delete Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vnfs_server_vnfs_servers_uuid_or_name_delete_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def delete_vnfs_server_vnfs_servers_uuid_or_name_delete_without_preload_content(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_vnfs_server_vnfs_servers_uuid_or_name_delete_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_vnfs_server_vnfs_servers_uuid_or_name_delete_serialize(
        self,
        uuid_or_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if uuid_or_name is not None:
            _path_params['uuid_or_name'] = uuid_or_name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/vnfs_servers/{uuid_or_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_vnfs_server_vnfs_servers_uuid_or_name_get(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Get Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vnfs_server_vnfs_servers_uuid_or_name_get_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_vnfs_server_vnfs_servers_uuid_or_name_get_with_http_info(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Get Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vnfs_server_vnfs_servers_uuid_or_name_get_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_vnfs_server_vnfs_servers_uuid_or_name_get_without_preload_content(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_vnfs_server_vnfs_servers_uuid_or_name_get_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_vnfs_server_vnfs_servers_uuid_or_name_get_serialize(
        self,
        uuid_or_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if uuid_or_name is not None:
            _path_params['uuid_or_name'] = uuid_or_name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/vnfs_servers/{uuid_or_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_vnfs_servers_vnfs_servers_get(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """List Vnfs Servers


        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vnfs_servers_vnfs_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_vnfs_servers_vnfs_servers_get_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """List Vnfs Servers


        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vnfs_servers_vnfs_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_vnfs_servers_vnfs_servers_get_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Vnfs Servers


        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_vnfs_servers_vnfs_servers_get_serialize(
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_vnfs_servers_vnfs_servers_get_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/vnfs_servers/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_vnfs_servers_search_vnfs_servers_get(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[Any] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Search Vnfs Servers


        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vnfs_servers_search_vnfs_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_vnfs_servers_search_vnfs_servers_get_with_http_info(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[Any] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Search Vnfs Servers


        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vnfs_servers_search_vnfs_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_vnfs_servers_search_vnfs_servers_get_without_preload_content(
        self,
        search_term: StrictStr,
        max_number_of_results: Optional[StrictInt] = None,
        similarity_threshold: Optional[Union[StrictFloat, StrictInt]] = None,
        manifest_filter: Optional[StrictStr] = None,
        lifecycle_state: Optional[Any] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search Vnfs Servers


        :param search_term: (required)
        :type search_term: str
        :param max_number_of_results:
        :type max_number_of_results: int
        :param similarity_threshold:
        :type similarity_threshold: float
        :param manifest_filter:
        :type manifest_filter: str
        :param lifecycle_state:
        :type lifecycle_state: LifecycleState
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_vnfs_servers_search_vnfs_servers_get_serialize(
            search_term=search_term,
            max_number_of_results=max_number_of_results,
            similarity_threshold=similarity_threshold,
            manifest_filter=manifest_filter,
            lifecycle_state=lifecycle_state,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_vnfs_servers_search_vnfs_servers_get_serialize(
        self,
        search_term,
        max_number_of_results,
        similarity_threshold,
        manifest_filter,
        lifecycle_state,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if search_term is not None:
            
            _query_params.append(('search_term', search_term))
            
        if max_number_of_results is not None:
            
            _query_params.append(('max_number_of_results', max_number_of_results))
            
        if similarity_threshold is not None:
            
            _query_params.append(('similarity_threshold', similarity_threshold))
            
        if manifest_filter is not None:
            
            _query_params.append(('manifest_filter', manifest_filter))
            
        if lifecycle_state is not None:
            
            _query_params.append(('lifecycle_state', lifecycle_state.value))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/search/vnfs_servers',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def start_vnfs_server_vnfs_servers_uuid_or_name_start_post(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Start Vnfs Server

        Start or restart a vNFS endpoint.

        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vnfs_server_vnfs_servers_uuid_or_name_start_post_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def start_vnfs_server_vnfs_servers_uuid_or_name_start_post_with_http_info(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Start Vnfs Server

        Start or restart a vNFS endpoint.

        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vnfs_server_vnfs_servers_uuid_or_name_start_post_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def start_vnfs_server_vnfs_servers_uuid_or_name_start_post_without_preload_content(
        self,
        uuid_or_name: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Start Vnfs Server

        Start or restart a vNFS endpoint.

        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._start_vnfs_server_vnfs_servers_uuid_or_name_start_post_serialize(
            uuid_or_name=uuid_or_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _start_vnfs_server_vnfs_servers_uuid_or_name_start_post_serialize(
        self,
        uuid_or_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if uuid_or_name is not None:
            _path_params['uuid_or_name'] = uuid_or_name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/vnfs_servers/{uuid_or_name}/start',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_vnfs_server_vnfs_servers_uuid_or_name_put(
        self,
        uuid_or_name: StrictStr,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Update Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vnfs_server_vnfs_servers_uuid_or_name_put_serialize(
            uuid_or_name=uuid_or_name,
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_vnfs_server_vnfs_servers_uuid_or_name_put_with_http_info(
        self,
        uuid_or_name: StrictStr,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Update Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vnfs_server_vnfs_servers_uuid_or_name_put_serialize(
            uuid_or_name=uuid_or_name,
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_vnfs_server_vnfs_servers_uuid_or_name_put_without_preload_content(
        self,
        uuid_or_name: StrictStr,
        name: Annotated[Optional[StrictStr], Field(description="Name")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="A UUID. If not provided, a UUID will be automatically generated.")] = None,
        version: Annotated[Optional[StrictStr], Field(description="Version")] = None,
        description: Annotated[Optional[StrictStr], Field(description="Short description")] = None,
        state: Annotated[Optional[Any], Field(description="Lifecycle state")] = None,
        tags: Annotated[Optional[List[StrictStr]], Field(description="List of tags for categorizing")] = None,
        extra: Annotated[Optional[Dict[str, Any]], Field(description="Optional dictionary for additional flexible information")] = None,
        parent: Annotated[Optional[StrictStr], Field(description="UUID of the parent object (previous version with same name)")] = None,
        created_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when created")] = None,
        modified_at: Annotated[Optional[StrictStr], Field(description="ISO 8601 timestamp when last modified")] = None,
        port: Annotated[Optional[Annotated[int, Field(lt=65536, strict=True, gt=0)]], Field(description="Port for the vNFS server. Auto-assigned if None.")] = None,
        skill_uuid: Annotated[Optional[StrictStr], Field(description="UUID of the skill to expose as a filesystem")] = None,
        protocol: Annotated[Optional[StrictStr], Field(description="Network filesystem protocol: 'webdav' or 'nfs'")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update Vnfs Server


        :param uuid_or_name: (required)
        :type uuid_or_name: str
        :param name: Name
        :type name: str
        :param uuid: A UUID. If not provided, a UUID will be automatically generated.
        :type uuid: str
        :param version: Version
        :type version: str
        :param description: Short description
        :type description: str
        :param state: Lifecycle state
        :type state: ManifestState
        :param tags: List of tags for categorizing
        :type tags: List[str]
        :param extra: Optional dictionary for additional flexible information
        :type extra: Dict[str, object]
        :param parent: UUID of the parent object (previous version with same name)
        :type parent: str
        :param created_at: ISO 8601 timestamp when created
        :type created_at: str
        :param modified_at: ISO 8601 timestamp when last modified
        :type modified_at: str
        :param port: Port for the vNFS server. Auto-assigned if None.
        :type port: int
        :param skill_uuid: UUID of the skill to expose as a filesystem
        :type skill_uuid: str
        :param protocol: Network filesystem protocol: 'webdav' or 'nfs'
        :type protocol: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_vnfs_server_vnfs_servers_uuid_or_name_put_serialize(
            uuid_or_name=uuid_or_name,
            name=name,
            uuid=uuid,
            version=version,
            description=description,
            state=state,
            tags=tags,
            extra=extra,
            parent=parent,
            created_at=created_at,
            modified_at=modified_at,
            port=port,
            skill_uuid=skill_uuid,
            protocol=protocol,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_vnfs_server_vnfs_servers_uuid_or_name_put_serialize(
        self,
        uuid_or_name,
        name,
        uuid,
        version,
        description,
        state,
        tags,
        extra,
        parent,
        created_at,
        modified_at,
        port,
        skill_uuid,
        protocol,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'tags': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if uuid_or_name is not None:
            _path_params['uuid_or_name'] = uuid_or_name
        # process the query parameters
        if name is not None:
            
            _query_params.append(('name', name))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if state is not None:
            
            _query_params.append(('state', state.value))
            
        if tags is not None:
            
            _query_params.append(('tags', tags))
            
        if extra is not None:
            
            _query_params.append(('extra', extra))
            
        if parent is not None:
            
            _query_params.append(('parent', parent))
            
        if created_at is not None:
            
            _query_params.append(('created_at', created_at))
            
        if modified_at is not None:
            
            _query_params.append(('modified_at', modified_at))
            
        if port is not None:
            
            _query_params.append(('port', port))
            
        if skill_uuid is not None:
            
            _query_params.append(('skill_uuid', skill_uuid))
            
        if protocol is not None:
            
            _query_params.append(('protocol', protocol))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/vnfs_servers/{uuid_or_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


