# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g4566c62-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ContentType(str, Enum):
    """
    Enum for snippet content types.
    """

    """
    allowed enum values
    """
    TEXT_SLASH_PLAIN = 'text/plain'
    TEXT_SLASH_MARKDOWN = 'text/markdown'
    TEXT_SLASH_HTML = 'text/html'
    TEXT_SLASH_XML = 'text/xml'
    TEXT_SLASH_CSS = 'text/css'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContentType from a JSON string"""
        return cls(json.loads(json_str))


