# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RunRequest(BaseModel):
    """
    RunRequest
    """ # noqa: E501
    request: StrictStr
    skills: Optional[List[StrictStr]] = None
    skills_dir: Optional[StrictStr] = None
    skills_upload_id: Optional[StrictStr] = None
    mcp_servers: Optional[Any] = None
    execution_mode: Optional[StrictStr] = None
    agent_env: Optional[Dict[str, StrictStr]] = None
    keep_workspace: Optional[StrictBool] = False
    use_runspace_server: Optional[StrictBool] = False
    runspace_server_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["request", "skills", "skills_dir", "skills_upload_id", "mcp_servers", "execution_mode", "agent_env", "keep_workspace", "use_runspace_server", "runspace_server_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mcp_servers
        if self.mcp_servers:
            _dict['mcp_servers'] = self.mcp_servers.to_dict()
        # set to None if skills_dir (nullable) is None
        # and model_fields_set contains the field
        if self.skills_dir is None and "skills_dir" in self.model_fields_set:
            _dict['skills_dir'] = None

        # set to None if skills_upload_id (nullable) is None
        # and model_fields_set contains the field
        if self.skills_upload_id is None and "skills_upload_id" in self.model_fields_set:
            _dict['skills_upload_id'] = None

        # set to None if mcp_servers (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_servers is None and "mcp_servers" in self.model_fields_set:
            _dict['mcp_servers'] = None

        # set to None if execution_mode (nullable) is None
        # and model_fields_set contains the field
        if self.execution_mode is None and "execution_mode" in self.model_fields_set:
            _dict['execution_mode'] = None

        # set to None if agent_env (nullable) is None
        # and model_fields_set contains the field
        if self.agent_env is None and "agent_env" in self.model_fields_set:
            _dict['agent_env'] = None

        # set to None if runspace_server_url (nullable) is None
        # and model_fields_set contains the field
        if self.runspace_server_url is None and "runspace_server_url" in self.model_fields_set:
            _dict['runspace_server_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "request": obj.get("request"),
            "skills": obj.get("skills"),
            "skills_dir": obj.get("skills_dir"),
            "skills_upload_id": obj.get("skills_upload_id"),
            "mcp_servers": AnyOf.from_dict(obj["mcp_servers"]) if obj.get("mcp_servers") is not None else None,
            "execution_mode": obj.get("execution_mode"),
            "agent_env": obj.get("agent_env"),
            "keep_workspace": obj.get("keep_workspace") if obj.get("keep_workspace") is not None else False,
            "use_runspace_server": obj.get("use_runspace_server") if obj.get("use_runspace_server") is not None else False,
            "runspace_server_url": obj.get("runspace_server_url")
        })
        return _obj


