#!/usr/bin/env python3
"""
Build pipeline for the 1-minute Skillberry Highlights video.
Run from docs/demo-videos/skillberry-store-highlights-video/:
    python3 build.py
"""
import subprocess, sys, wave
from pathlib import Path

try:
    from gtts import gTTS
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "gtts", "-q"])
    from gtts import gTTS

HERE        = Path(__file__).parent.resolve()
VIDEOS_ROOT = HERE.parent          # docs/demo-videos/
OUT         = HERE / "out"
TMP         = OUT / "tts_segments"
SRT         = HERE / "captions.srt"
OUT.mkdir(exist_ok=True)
TMP.mkdir(exist_ok=True)

FPS         = 30
TOTAL_SEC   = 65          # widened from 60s — 5 scenes had slots too short for TTS at 1.8×
SAMPLE_RATE = 44100
SILENCE_THR = 200

# scene name, start_frame, slot_sec, spoken text
# Slots must satisfy: (raw_gTTS_dur / 1.8) + 0.4 <= slot_sec
# start_frame values must match SEGMENTS in src/highlights/constants.ts
SCENES = [
    ("01_intro", 0, 5,
     "Skillberry Store. A smart skills repository for agentic workflows."),

    ("02_install", 150, 7,           # was 6 — TTS at 1.8× ran 6.5s, got truncated
     "Install with pip, start with make docker-run. "
     "Web UI on port 8002, REST API on 8000. Live in under a minute."),

    ("03_import", 360, 8,            # was 7 — TTS at 1.8× ran 7.5s, got truncated
     "Import any Anthropic skill via GitHub URL, zip file, or local folder. "
     "One call — 66 tools and 43 snippets imported instantly."),

    ("04_skills_ui", 600, 7,
     "The Skills library auto-tags every skill with quality, performance, and security scores "
     "generated by the AI plugins on import."),

    ("05_execute", 810, 8,           # was 7 — TTS at 1.8× ran 7.5s, got truncated
     "Execute any tool with a JSON body — via the UI dialog or the sbs CLI. "
     "Every execution runs in a Docker sandbox, fully isolated."),

    ("06_plugin_eval", 1050, 7,
     "The Content Evaluator and Security Scanner automatically score skills on import. "
     "The Summarizer scored 9 for quality, 8 for performance, 8 for security."),

    ("07_plugin_sec", 1260, 7,       # was 6 — TTS at 1.8× ran 6.5s, got truncated ("skills." cut)
     "Three more plugins: Deduplicator finds near-identical skills, "
     "Creator generates code from text, "
     "Optimizer runs Claude Code to improve skills."),

    ("08_vmcp", 1470, 7,             # was 6 — TTS at 1.8× ran 6.3s, got truncated
     "Virtual MCP Servers give each skill its own MCP endpoint. "
     "Virtual NFS mounts skills as filesystems. "
     "Prometheus and Jaeger built in."),

    ("09_outro", 1680, 9,
     "That's Skillberry Store — one service for every skill your agents need. "
     "Find us at github.com slash skillberry-ai slash skillberry-store."),
]


def frames_to_sec(frames): return frames / FPS
def sec_to_samples(sec):   return int(sec * SAMPLE_RATE)

def mp3_to_wav(mp3, wav):
    subprocess.check_call(["ffmpeg","-y","-loglevel","error","-i",str(mp3),"-ar",str(SAMPLE_RATE),"-ac","1",str(wav)])

def get_audio_duration(mp3):
    r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                        "-of","default=noprint_wrappers=1:nokey=1",str(mp3)], capture_output=True, text=True)
    return float(r.stdout.strip())

def read_wav_pcm(wav):
    tmp = wav.with_suffix(".rs.wav")
    subprocess.check_call(["ffmpeg","-y","-loglevel","error","-i",str(wav),"-ar",str(SAMPLE_RATE),"-ac","1",str(tmp)])
    with wave.open(str(tmp)) as wf:
        data = wf.readframes(wf.getnframes())
    tmp.unlink(missing_ok=True)
    return data


# ── SRT helpers ───────────────────────────────────────────────────────────

import struct

def detect_speech_bounds(wav_path):
    with wave.open(str(wav_path)) as wf:
        n = wf.getnframes(); rate = wf.getframerate()
        raw = wf.readframes(n)
    samples = struct.unpack(f"<{n}h", raw)
    start = 0
    for i, s in enumerate(samples):
        if abs(s) > SILENCE_THR:
            start = max(0, i - int(rate * 0.05)); break
    end = n - 1
    for i in range(n-1,-1,-1):
        if abs(samples[i]) > SILENCE_THR:
            end = min(n-1, i + int(rate * 0.05)); break
    return start / rate, end / rate

def srt_time(sec):
    ms = int(round(sec * 1000))
    h, ms = divmod(ms, 3_600_000); m, ms = divmod(ms, 60_000); s, ms = divmod(ms, 1_000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def split_lines(text, max_chars=58):
    words = text.split(); lines = []; cur = ""
    for w in words:
        cand = (cur + " " + w).strip()
        if len(cand) <= max_chars: cur = cand
        else:
            if cur: lines.append(cur)
            cur = w
    if cur: lines.append(cur)
    return lines


# ── steps ─────────────────────────────────────────────────────────────────

def generate_tts():
    print("Step 1  TTS segments ...")
    for name, start_frame, slot_sec, text in SCENES:
        mp3 = TMP / f"{name}.mp3"
        fast_mp3 = TMP / f"{name}_fast.mp3"
        print(f"  {name} ...", end=" ", flush=True)
        gTTS(text=text, lang="en", slow=False).save(str(mp3))
        dur = get_audio_duration(mp3)
        target = slot_sec - 0.4
        print(f"{dur:.1f}s / {slot_sec}s", end="")
        if dur > target:
            ratio = min(dur / target, 1.8)
            print(f" → {ratio:.2f}x", end="")
            subprocess.check_call(["ffmpeg","-y","-loglevel","error","-i",str(mp3),"-af",f"atempo={ratio:.4f}",str(fast_mp3)])
            fast_dur = get_audio_duration(fast_mp3)
            print(f" → {fast_dur:.1f}s", end="")
            if fast_dur <= target + 0.1:
                fast_mp3.rename(mp3)
            else:
                tmp = TMP / f"{name}_tr.mp3"
                subprocess.check_call(["ffmpeg","-y","-loglevel","error","-i",str(fast_mp3),"-t",str(target),"-c","copy",str(tmp)])
                tmp.rename(mp3); fast_mp3.unlink(missing_ok=True)
        print()


def assemble_wav():
    print("\nStep 2  Assembling voiceover WAV ...")
    buf = bytearray(sec_to_samples(TOTAL_SEC) * 2)
    for name, start_frame, _, _ in SCENES:
        mp3 = TMP / f"{name}.mp3"
        wav = TMP / f"{name}.wav"
        mp3_to_wav(mp3, wav)
        pcm = read_wav_pcm(wav)
        off = sec_to_samples(frames_to_sec(start_frame)) * 2
        end = off + len(pcm)
        if end > len(buf): end = len(buf); pcm = pcm[:end-off]
        buf[off:end] = pcm
    out_wav = OUT / "voiceover.wav"
    with wave.open(str(out_wav),"w") as wf:
        wf.setnchannels(1); wf.setsampwidth(2); wf.setframerate(SAMPLE_RATE)
        wf.writeframes(bytes(buf))
    print(f"  → {out_wav}")
    return out_wav


def build_srt():
    print("\nStep 3  Building captions.srt from actual speech timing ...")
    blocks = []; idx = 1
    for name, start_frame, _, text in SCENES:
        scene_sec = start_frame / FPS
        mp3 = TMP / f"{name}.mp3"
        wav = TMP / f"{name}_cap.wav"
        mp3_to_wav(mp3, wav)
        sp0, sp1 = detect_speech_bounds(wav)
        wav.unlink(missing_ok=True)
        abs0 = scene_sec + sp0; abs1 = scene_sec + sp1
        lines  = split_lines(text)
        chunks = ["\n".join(lines[i:i+2]) for i in range(0,len(lines),2)]
        n = len(chunks)
        if not n: continue
        dur = (abs1 - abs0) / n
        for i, chunk in enumerate(chunks):
            blocks.append((idx, abs0 + i*dur, abs0 + (i+1)*dur - 0.05, chunk))
            idx += 1
    with open(SRT,"w",encoding="utf-8") as f:
        for num, t0, t1, txt in blocks:
            f.write(f"{num}\n{srt_time(t0)} --> {srt_time(t1)}\n{txt}\n\n")
    print(f"  → {len(blocks)} blocks → {SRT}")


def render_video():
    silent = OUT / "skillberry-highlights-silent.mp4"
    if silent.exists():
        print(f"\nStep 4  Silent MP4 already exists, skipping render.")
        return silent
    print("\nStep 4  Rendering Remotion composition ...")
    subprocess.check_call([
        "npx","remotion","render",
        "--config=remotion.highlights.config.ts",
        "SkillberryHighlights", str(silent),
    ], cwd=str(VIDEOS_ROOT))
    print(f"  → {silent}")
    return silent


def merge_and_caption(silent, wav):
    audio  = OUT / "skillberry-highlights-audio.mp4"
    final  = OUT / "skillberry-highlights-final.mp4"
    srt_esc = str(SRT).replace(":", "\\:")
    print("\nStep 5  Merging audio ...")
    subprocess.check_call([
        "ffmpeg","-y","-loglevel","warning",
        "-i",str(silent),"-i",str(wav),
        "-map","0:v:0","-map","1:a:0",
        "-c:v","copy","-c:a","aac","-b:a","192k","-ar","48000","-ac","2",
        str(audio)])
    print("Step 6  Burning captions ...")
    subprocess.check_call([
        "ffmpeg","-y","-loglevel","warning",
        "-i",str(audio),
        "-vf",(f"subtitles={srt_esc}:force_style='FontName=Arial,FontSize=14,Bold=0,"
               "PrimaryColour=&H00FFFFFF,OutlineColour=&H80000000,Outline=2,Shadow=1,"
               "Alignment=2,MarginV=28'"),
        "-c:a","copy",str(final)])
    print(f"\n  ✅  {final}  ({final.stat().st_size/1e6:.0f} MB)")


if __name__ == "__main__":
    print("\n═══ Skillberry Highlights — Build Pipeline ═══\n")
    generate_tts()
    wav    = assemble_wav()
    build_srt()
    silent = render_video()
    merge_and_caption(silent, wav)
    print()
