# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7e7e4c-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.content_type import ContentType

class TestContentType(unittest.TestCase):
    """ContentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentType(self):
        """Test ContentType"""
        # inst = ContentType()

if __name__ == '__main__':
    unittest.main()
