# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g6587ce1
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.extra2 import Extra2

class TestExtra2(unittest.TestCase):
    """Extra2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Extra2:
        """Test Extra2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Extra2`
        """
        model = Extra2()
        if include_optional:
            return Extra2(
            )
        else:
            return Extra2(
        )
        """

    def testExtra2(self):
        """Test Extra2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
