# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.plugin_enabled_update import PluginEnabledUpdate

class TestPluginEnabledUpdate(unittest.TestCase):
    """PluginEnabledUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginEnabledUpdate:
        """Test PluginEnabledUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginEnabledUpdate`
        """
        model = PluginEnabledUpdate()
        if include_optional:
            return PluginEnabledUpdate(
                enabled = True
            )
        else:
            return PluginEnabledUpdate(
                enabled = True,
        )
        """

    def testPluginEnabledUpdate(self):
        """Test PluginEnabledUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
