# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g37a29ee-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.tool_params_schema import ToolParamsSchema

class TestToolParamsSchema(unittest.TestCase):
    """ToolParamsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolParamsSchema:
        """Test ToolParamsSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolParamsSchema`
        """
        model = ToolParamsSchema()
        if include_optional:
            return ToolParamsSchema(
                type = 'object',
                properties = {
                    'key' : {
                        'key' : null
                        }
                    },
                required = [
                    ''
                    ],
                optional = [
                    ''
                    ]
            )
        else:
            return ToolParamsSchema(
        )
        """

    def testToolParamsSchema(self):
        """Test ToolParamsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
