# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.sast_api import SastApi


class TestSastApi(unittest.TestCase):
    """SastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SastApi()

    def tearDown(self) -> None:
        pass

    def test_sast_fix_endpoint(self) -> None:
        """Test case for sast_fix_endpoint

        Fix Endpoint
        """
        pass

    def test_sast_scan_endpoint(self) -> None:
        """Test case for sast_scan_endpoint

        Scan Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
