# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.dedupe_api import DedupeApi


class TestDedupeApi(unittest.TestCase):
    """DedupeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DedupeApi()

    def tearDown(self) -> None:
        pass

    def test_dedupe_delete_decision(self) -> None:
        """Test case for dedupe_delete_decision

        Delete Decision
        """
        pass

    def test_dedupe_keep_decision(self) -> None:
        """Test case for dedupe_keep_decision

        Keep Decision
        """
        pass

    def test_dedupe_list_decisions(self) -> None:
        """Test case for dedupe_list_decisions

        List Decisions
        """
        pass


if __name__ == '__main__':
    unittest.main()
