# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g689a0f7-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.plugins_api import PluginsApi


class TestPluginsApi(unittest.TestCase):
    """PluginsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PluginsApi()

    def tearDown(self) -> None:
        pass

    def test_get_plugin_info_plugins_plugin_name_get(self) -> None:
        """Test case for get_plugin_info_plugins_plugin_name_get

        Get plugin information
        """
        pass

    def test_import_tools_plugins_mcp_importer_import_tools_post(self) -> None:
        """Test case for import_tools_plugins_mcp_importer_import_tools_post

        Import Tools
        """
        pass

    def test_list_plugins_plugins_get(self) -> None:
        """Test case for list_plugins_plugins_get

        List all plugins
        """
        pass


if __name__ == '__main__':
    unittest.main()
