# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.skillberry_plugin_mcp_importer_plugin_skillberry_plugin_mcp_importer_get_router_locals_import_request import SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest

class TestSkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest(unittest.TestCase):
    """SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest:
        """Test SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest`
        """
        model = SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest()
        if include_optional:
            return SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest(
                mcp_url = '',
                create_skill = True,
                skill_name = '',
                tags = [
                    ''
                    ]
            )
        else:
            return SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest(
                mcp_url = '',
        )
        """

    def testSkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest(self):
        """Test SkillberryPluginMcpImporterPluginSkillberryPluginMcpImporterGetRouterLocalsImportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
