# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.optimize_skill_request import OptimizeSkillRequest

class TestOptimizeSkillRequest(unittest.TestCase):
    """OptimizeSkillRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptimizeSkillRequest:
        """Test OptimizeSkillRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptimizeSkillRequest`
        """
        model = OptimizeSkillRequest()
        if include_optional:
            return OptimizeSkillRequest(
                skill_uuid = '',
                output_skill_name = '',
                include_metadata = True,
                trajectories_dir = '',
                additional_context_dir = '',
                agent_env = {
                    'key' : ''
                    },
                execution_mode = '',
                max_turns = 56,
                optimization_goal = ''
            )
        else:
            return OptimizeSkillRequest(
                skill_uuid = '',
        )
        """

    def testOptimizeSkillRequest(self):
        """Test OptimizeSkillRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
