# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.skillberry_plugin_skillssh_importer_plugin_skillberry_plugin_skills_sh_importer_get_router_locals_import_request import SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest

class TestSkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest(unittest.TestCase):
    """SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest:
        """Test SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest`
        """
        model = SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest()
        if include_optional:
            return SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest(
                skill_ids = [
                    ''
                    ],
                tags = [
                    ''
                    ],
                fetch_audits = True,
                skills_sh_token = ''
            )
        else:
            return SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest(
                skill_ids = [
                    ''
                    ],
        )
        """

    def testSkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest(self):
        """Test SkillberryPluginSkillsshImporterPluginSkillberryPluginSkillsShImporterGetRouterLocalsImportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
