# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.5.5-313-gee35082-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_get_metrics_admin_metrics_get(self) -> None:
        """Test case for get_metrics_admin_metrics_get

        Get Metrics
        """
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_purge_all_data_admin_purge_all_delete(self) -> None:
        """Test case for purge_all_data_admin_purge_all_delete

        Purge All Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
