# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.simulate_api import SimulateApi


class TestSimulateApi(unittest.TestCase):
    """SimulateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulateApi()

    def tearDown(self) -> None:
        pass

    def test_simulate_active(self) -> None:
        """Test case for simulate_active

        Active
        """
        pass

    def test_simulate_simulate(self) -> None:
        """Test case for simulate_simulate

        Simulate
        """
        pass

    def test_simulate_simulate_status(self) -> None:
        """Test case for simulate_simulate_status

        Simulate Status
        """
        pass

    def test_simulate_teardown(self) -> None:
        """Test case for simulate_teardown

        Teardown
        """
        pass

    def test_simulate_toggle(self) -> None:
        """Test case for simulate_toggle

        Toggle
        """
        pass


if __name__ == '__main__':
    unittest.main()
