# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_backup_all_data(self) -> None:
        """Test case for backup_all_data

        Backup All Data
        """
        pass

    def test_get_changes_count(self) -> None:
        """Test case for get_changes_count

        Get Changes Count
        """
        pass

    def test_get_metrics(self) -> None:
        """Test case for get_metrics

        Get Metrics
        """
        pass

    def test_health_check(self) -> None:
        """Test case for health_check

        Health Check
        """
        pass

    def test_purge_all_data(self) -> None:
        """Test case for purge_all_data

        Purge All Data
        """
        pass

    def test_readiness_check(self) -> None:
        """Test case for readiness_check

        Readiness Check
        """
        pass

    def test_restore_all_data(self) -> None:
        """Test case for restore_all_data

        Restore All Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
