# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g37a29ee-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.lifecycle_state import LifecycleState

class TestLifecycleState(unittest.TestCase):
    """LifecycleState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLifecycleState(self):
        """Test LifecycleState"""
        # inst = LifecycleState()

if __name__ == '__main__':
    unittest.main()
