# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.evaluator_api import EvaluatorApi


class TestEvaluatorApi(unittest.TestCase):
    """EvaluatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EvaluatorApi()

    def tearDown(self) -> None:
        pass

    def test_evaluator_evaluate_endpoint(self) -> None:
        """Test case for evaluator_evaluate_endpoint

        Evaluate Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
