# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.add_tool_from_code_request import AddToolFromCodeRequest

class TestAddToolFromCodeRequest(unittest.TestCase):
    """AddToolFromCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddToolFromCodeRequest:
        """Test AddToolFromCodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddToolFromCodeRequest`
        """
        model = AddToolFromCodeRequest()
        if include_optional:
            return AddToolFromCodeRequest(
                code = '',
                selected_func = '',
                update = True,
                module_name = ''
            )
        else:
            return AddToolFromCodeRequest(
                code = '',
        )
        """

    def testAddToolFromCodeRequest(self):
        """Test AddToolFromCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
