# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.mcp_importer_api import McpImporterApi


class TestMcpImporterApi(unittest.TestCase):
    """McpImporterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = McpImporterApi()

    def tearDown(self) -> None:
        pass

    def test_mcp_importer_import_tools(self) -> None:
        """Test case for mcp_importer_import_tools

        Import Tools
        """
        pass


if __name__ == '__main__':
    unittest.main()
