# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.5.5-211-g4be6ef7-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.snippets_api import SnippetsApi


class TestSnippetsApi(unittest.TestCase):
    """SnippetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnippetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_snippet_snippets_post(self) -> None:
        """Test case for create_snippet_snippets_post

        Create Snippet
        """
        pass

    def test_delete_snippet_snippets_name_delete(self) -> None:
        """Test case for delete_snippet_snippets_name_delete

        Delete Snippet
        """
        pass

    def test_get_snippet_snippets_name_get(self) -> None:
        """Test case for get_snippet_snippets_name_get

        Get Snippet
        """
        pass

    def test_list_snippets_snippets_get(self) -> None:
        """Test case for list_snippets_snippets_get

        List Snippets
        """
        pass

    def test_search_snippets_search_snippets_get(self) -> None:
        """Test case for search_snippets_search_snippets_get

        Search Snippets
        """
        pass

    def test_update_snippet_snippets_name_put(self) -> None:
        """Test case for update_snippet_snippets_name_put

        Update Snippet
        """
        pass


if __name__ == '__main__':
    unittest.main()
