# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g689a0f7-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_backup_all_data_admin_backup_get(self) -> None:
        """Test case for backup_all_data_admin_backup_get

        Backup All Data
        """
        pass

    def test_get_changes_count_changes_get(self) -> None:
        """Test case for get_changes_count_changes_get

        Get Changes Count
        """
        pass

    def test_get_metrics_admin_metrics_get(self) -> None:
        """Test case for get_metrics_admin_metrics_get

        Get Metrics
        """
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_purge_all_data_admin_purge_all_delete(self) -> None:
        """Test case for purge_all_data_admin_purge_all_delete

        Purge All Data
        """
        pass

    def test_readiness_check_health_ready_get(self) -> None:
        """Test case for readiness_check_health_ready_get

        Readiness Check
        """
        pass

    def test_restore_all_data_admin_restore_post(self) -> None:
        """Test case for restore_all_data_admin_restore_post

        Restore All Data
        """
        pass


if __name__ == '__main__':
    unittest.main()
