# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: g4566c62-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.tool_schema import ToolSchema

class TestToolSchema(unittest.TestCase):
    """ToolSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolSchema:
        """Test ToolSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolSchema`
        """
        model = ToolSchema()
        if include_optional:
            return ToolSchema(
                name = '',
                uuid = '',
                version = '',
                description = '',
                state = 'unknown',
                tags = [
                    ''
                    ],
                extra = {
                    'key' : null
                    },
                created_at = '',
                modified_at = '',
                module_name = '',
                programming_language = 'python',
                packaging_format = 'code',
                params = skillberry_store_sdk.models.tool_params_schema.ToolParamsSchema(
                    type = 'object', 
                    properties = {
                        'key' : {
                            'key' : null
                            }
                        }, 
                    required = [
                        ''
                        ], 
                    optional = [
                        ''
                        ], ),
                returns = skillberry_store_sdk.models.tool_returns_schema.ToolReturnsSchema(
                    type = '', 
                    description = '', ),
                dependencies = [
                    ''
                    ]
            )
        else:
            return ToolSchema(
        )
        """

    def testToolSchema(self):
        """Test ToolSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
