# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.tools_api import ToolsApi


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolsApi()

    def tearDown(self) -> None:
        pass

    def test_add_tool_from_code(self) -> None:
        """Test case for add_tool_from_code

        Add Tool From Code
        """
        pass

    def test_add_tool_from_python(self) -> None:
        """Test case for add_tool_from_python

        Add Tool From Python
        """
        pass

    def test_create_tool(self) -> None:
        """Test case for create_tool

        Create Tool
        """
        pass

    def test_delete_tool(self) -> None:
        """Test case for delete_tool

        Delete Tool
        """
        pass

    def test_execute_tool(self) -> None:
        """Test case for execute_tool

        Execute Tool
        """
        pass

    def test_get_tool(self) -> None:
        """Test case for get_tool

        Get Tool
        """
        pass

    def test_get_tool_module(self) -> None:
        """Test case for get_tool_module

        Get Tool Module
        """
        pass

    def test_list_tools(self) -> None:
        """Test case for list_tools

        List Tools
        """
        pass

    def test_search_tools(self) -> None:
        """Test case for search_tools

        Search Tools
        """
        pass

    def test_tool_facets(self) -> None:
        """Test case for tool_facets

        Tool Facets
        """
        pass

    def test_update_tool(self) -> None:
        """Test case for update_tool

        Update Tool
        """
        pass


if __name__ == '__main__':
    unittest.main()
