# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.anthropic_skill_generator_api import AnthropicSkillGeneratorApi


class TestAnthropicSkillGeneratorApi(unittest.TestCase):
    """AnthropicSkillGeneratorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnthropicSkillGeneratorApi()

    def tearDown(self) -> None:
        pass

    def test_anthropic_skill_generator_generate_skill_endpoint(self) -> None:
        """Test case for anthropic_skill_generator_generate_skill_endpoint

        Generate Skill Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
