# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.models.create_snippet_request import CreateSnippetRequest

class TestCreateSnippetRequest(unittest.TestCase):
    """CreateSnippetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSnippetRequest:
        """Test CreateSnippetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSnippetRequest`
        """
        model = CreateSnippetRequest()
        if include_optional:
            return CreateSnippetRequest(
                description = '',
                name = ''
            )
        else:
            return CreateSnippetRequest(
                description = '',
        )
        """

    def testCreateSnippetRequest(self):
        """Test CreateSnippetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
