# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.skill_optimizer_api import SkillOptimizerApi


class TestSkillOptimizerApi(unittest.TestCase):
    """SkillOptimizerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SkillOptimizerApi()

    def tearDown(self) -> None:
        pass

    def test_skill_optimizer_optimize_skill_endpoint(self) -> None:
        """Test case for skill_optimizer_optimize_skill_endpoint

        Optimize Skill Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
