# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.5.5-313-gee35082-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.skills_api import SkillsApi


class TestSkillsApi(unittest.TestCase):
    """SkillsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SkillsApi()

    def tearDown(self) -> None:
        pass

    def test_create_skill_skills_post(self) -> None:
        """Test case for create_skill_skills_post

        Create Skill
        """
        pass

    def test_delete_skill_skills_name_delete(self) -> None:
        """Test case for delete_skill_skills_name_delete

        Delete Skill
        """
        pass

    def test_export_anthropic_skill_skills_name_export_anthropic_get(self) -> None:
        """Test case for export_anthropic_skill_skills_name_export_anthropic_get

        Export Anthropic Skill
        """
        pass

    def test_get_skill_skills_name_get(self) -> None:
        """Test case for get_skill_skills_name_get

        Get Skill
        """
        pass

    def test_import_anthropic_skill_skills_import_anthropic_post(self) -> None:
        """Test case for import_anthropic_skill_skills_import_anthropic_post

        Import Anthropic Skill
        """
        pass

    def test_list_skills_skills_get(self) -> None:
        """Test case for list_skills_skills_get

        List Skills
        """
        pass

    def test_search_skills_search_skills_get(self) -> None:
        """Test case for search_skills_search_skills_get

        Search Skills
        """
        pass

    def test_update_skill_skills_name_put(self) -> None:
        """Test case for update_skill_skills_name_put

        Update Skill
        """
        pass


if __name__ == '__main__':
    unittest.main()
