# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.dast_api import DastApi


class TestDastApi(unittest.TestCase):
    """DastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DastApi()

    def tearDown(self) -> None:
        pass

    def test_dast_scan_endpoint(self) -> None:
        """Test case for dast_scan_endpoint

        Scan Endpoint
        """
        pass

    def test_dast_scan_status(self) -> None:
        """Test case for dast_scan_status

        Scan Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
