# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7d20e0-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.provenance_api import ProvenanceApi


class TestProvenanceApi(unittest.TestCase):
    """ProvenanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProvenanceApi()

    def tearDown(self) -> None:
        pass

    def test_provenance_check_endpoint(self) -> None:
        """Test case for provenance_check_endpoint

        Check Endpoint
        """
        pass

    def test_provenance_recheck_endpoint(self) -> None:
        """Test case for provenance_recheck_endpoint

        Recheck Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
