# coding: utf-8

"""
    skillberry

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: gf7e7e4c-dirty
    Contact: eranra@il.ibm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_store_sdk.api.tools_api import ToolsApi


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolsApi()

    def tearDown(self) -> None:
        pass

    def test_add_tool_from_python_tools_add_post(self) -> None:
        """Test case for add_tool_from_python_tools_add_post

        Add Tool From Python
        """
        pass

    def test_create_tool_tools_post(self) -> None:
        """Test case for create_tool_tools_post

        Create Tool
        """
        pass

    def test_delete_tool_tools_name_delete(self) -> None:
        """Test case for delete_tool_tools_name_delete

        Delete Tool
        """
        pass

    def test_execute_tool_tools_name_execute_post(self) -> None:
        """Test case for execute_tool_tools_name_execute_post

        Execute Tool
        """
        pass

    def test_get_tool_module_tools_name_module_get(self) -> None:
        """Test case for get_tool_module_tools_name_module_get

        Get Tool Module
        """
        pass

    def test_get_tool_tools_name_get(self) -> None:
        """Test case for get_tool_tools_name_get

        Get Tool
        """
        pass

    def test_list_tools_tools_get(self) -> None:
        """Test case for list_tools_tools_get

        List Tools
        """
        pass

    def test_search_tools_search_tools_get(self) -> None:
        """Test case for search_tools_search_tools_get

        Search Tools
        """
        pass

    def test_update_tool_tools_name_put(self) -> None:
        """Test case for update_tool_tools_name_put

        Update Tool
        """
        pass


if __name__ == '__main__':
    unittest.main()
